### ISSUE TITLE
为什么运行时报错：“PlayerKitDemo.app” couldn’t be opened because you don’t have permission to view it

### ISSUE THREAD

**Issue by sharehoney** [poholo/PlayerKit#10]
真机 编译可以通过，但一旦运行 就 报错如下：

The file “PlayerKitDemo.app” couldn’t be opened because you don’t have permission to view it.
Domain: NSCocoaErrorDomain
Code: 257
Failure Reason: You don’t have permission.
Recovery Suggestion: To view or change permissions, select the item in the Finder and choose File > Get Info.
User Info: {
    NSFilePath = "/Users/leebeen/Library/Developer/Xcode/DerivedData/PlayerKitDemo-hivdczixikqipffrhxhcwhkfruzb/Build/Products/Debug-iphoneos/PlayerKitDemo.app";
}
--
The operation couldn’t be completed. Permission denied
Domain: NSPOSIXErrorDomain
Code: 13
Failure Reason: Permission denied
--

System Information

macOS Version 10.15.7 (Build 19H114)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-08-29T11:41:30+08:00

**Comment by sharehoney** [comment]
刚才新建了一个空白的工程，试着将demo中的源码复制过来，但是问题依旧。

挺奇怪的啊。

**Comment by poholo** [comment]
swift 工程 ? oc工程? 还是swiftUI工程呢?

**Comment by sharehoney** [comment]
谢谢回复，是OC工程。

**Comment by poholo** [comment]
只保留一个PlayerKitDemo工程了? 
这个是编译阶段没有报错, copy .app到模拟器真机就失败了,
我刚测试有一个PlayerKitDemo没有问题,真机/模拟器均可.
后面我猜测你可能运行的问题, 又重新git clone一份, 然后编译无问题, 会在copy到设备时执行报
```
Details

Executable Not Found
Domain: DVTMachOErrorDomain
Code: 5
Recovery Suggestion: /Users/majiancheng/Library/Developer/Xcode/DerivedData/PlayerKitDemo-gmhzuqcifcfbqibeubvgmatogtqc/Build/Products/Debug-iphoneos/PlayerKitDemo.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.
--


System Information

macOS Version 11.4 (Build 20F71)
Xcode 12.5.1 (18212) (Build 12E507)
Timestamp: 2021-08-31T10:57:34+08:00
```

1. 删除重名工程, 编译运行 - 未解决
2. clear - 删除DerivedData - 未解决
3. 重启 未尝试


这个问题目前看时xcode问题, 待重启后再编辑回复此条. 您可以自行尝试一下

**Comment by sharehoney** [comment]
谢谢回复。

您的Xcode是12.5.x 是吧，那可能是我的版本低了，我的是12.4。

**Comment by poholo** [comment]
3.  重启  可以正常run 

您自己看看问题哈, 我这边无法复现您的问题, 估计跟xcode版本也没啥关系吧.

**Comment by poholo** [comment]
可能是多个同名工程造成, 抑或是xcode原因, 按照记录操作即可.
