### ISSUE TITLE
IjkPlayer子线程的问题

### ISSUE THREAD

**Issue by lucking** [poholo/PlayerKit#11]
尊敬的马老师，这是我 微信号 13022155071，希望能加下您 ，请教一个问题、
我编译的 IjkPlayer 第一次播放有子线程的问题，按这种方式修改会主线程卡死（解决IJK在子线程执行UI的问题 https://blog.51cto.com/mlcmlc/4900273）

**Comment by poholo** [comment]
你好，你提交的地址已经不存在，线程ijk卡丝的问题，其实就是在IJKSDLGLView主线程检查问题，请通过一下几个仓库了解
ijkplayer源码修改见：https://github.com/poholo/ijkplayer (源码修改见几个commit) -- 自己编译自定
ijkplayer打包好的库：https://github.com/poholo/MCIJKPlayer  pod 'MCIJKPlayer' （无需编译，pod集成）
MCPlayerKit通用测试库：https://github.com/poholo/MCPlayerKit （里面有现成的Demo）
有问题提pr，感谢
