### ISSUE TITLE
关于ijk中IJKSDLGLView.m文件的线程问题

### ISSUE THREAD

**Issue by dagundejuzi** [poholo/PlayerKit#5]
我是在ijk的仓库看到你的提交，想请教下关于这个文件的线程问题。ijk里的文件比对差异太多了，可能有看漏的。

1、在IJKSDLGLView.m中的`-invalidateRenderBuffer` 方法，在调用 `[self display:nil]; `之前，还是应该加上
``` 
if (_isRenderBufferInvalidated)
     [self display:nil];
```
判断，不然会概率性的崩在下面这句：
```
if (!IJK_GLES2_Renderer_renderOverlay(_renderer, overlay))
        ALOGE("[EGL] IJK_GLES2_render failed\n");
```
2、第一次进入还是会卡，-displayInternal: 这个方法中的
```
[[self eaglLayer] setContentsScale:_scaleFactor];
```
和
```
[_context renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer*)self.layer];
```
我都用`dispatch_async(dispatch_get_main_queue(), ^{   });`包起来了。你的修改似乎没动这里，请问是怎么做的？

**Comment by poholo** [comment]
我的方案是比较取巧，造成卡线程的原因是iOSx开始苹果对一些基本的属性get做了UI线程检查，这会造成线程之间切换等待，什么什么的吧。
所以我在初始化的时候直接一次把一些检查UI获取的东西通过中间变量承接，这样就不需要到这块做线程切换来处理。 你可以通过文件比较器看看我对IJKSDLGLView.m修改

http://poholo.github.io/2019/09/19/Apple-x-more/
