### ISSUE TITLE
视频播放卡顿，能看出来问题吗

### ISSUE THREAD

**Issue by Jayxiang** [poholo/PlayerKit#7]
网络视频卡顿，但是下载后放本地没问题。
[视频地址](https://kb-test-hz.oss-cn-hangzhou.aliyuncs.com/27188B8E7F8E3-37DC-4AEB-B28B-CEC08F88507C-2881-00000318E7046143.mp4)

**Comment by poholo** [comment]
好的 我也看到这个问题了

**Comment by poholo** [comment]
我用原版IJKPlayer看了也有此问题，你可以提到ijkplayer原repo

或者此类视频用AVPlayer播放看起来是没有问题的（此类视频估计是剪辑拼接有什么问题吧）

可以用 
```
_playerKit = [[MCPlayerKit alloc] initWithPlayerView:self.playerView.playerView];
_playerKit.playerCoreType = MCPlayerCoreAVPlayer;
```
@Jayxiang

**Comment by Jayxiang** [comment]
是的，但是 AVPlayer 有的视频播放不了。而且这种视频也不知道怎么判断。目前没有完美的方法。
