### ISSUE TITLE
player高度变化时opengl渲染的时候会不准确

### ISSUE THREAD

**Issue by ChavezChen** [poholo/PlayerKit#8]
你好楼主，新入坑音视频的开发，发现了下面这个问题，请问有什么好的解决方案吗？修改播放器的高度时，渲染的视频的左右会跳动漏出layer的底色

https://user-images.githubusercontent.com/13866359/115376482-4fa7dc00-a201-11eb-9f67-71743566aa00.MOV
可以下载视频看一下场景

**Comment by poholo** [comment]
这个应该是用的ijk，鉴于这个库目前主要开发者不再维护，修复glview渲染涉及层次较深，可以用avplayer代替
`_playerKit.playerCoreType = MCPlayerCoreAVPlayer;`
感谢
